DemoSinai/Models/Department.cs
namespace DemoSinai.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Department
    {
        [Key]
        public int DepartmentId { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [MaxLength(50, ErrorMessage = "El campo {0} puede tener máximo {1} carateres de longitud.")]
        [Index("Department_Name_Index", IsUnique = true)]
        public string Name { get; set; }

        public int DeparmentCode { get; set; }

        public virtual ICollection<City> Cities { get; set; }
    }
}

DemoSinai/Models/ImportView.cs
namespace DemoSinai.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public class ImportView
    {
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Archivo de Departamentos")]
        public HttpPostedFileBase DeparmentsFile { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        [Display(Name = "Archivo de Ciudades")]
        public HttpPostedFileBase CitiesFile { get; set; }
    }
}

DemoSinai/Controllers/DepartmentsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
namespace DemoSinai.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using Models;
    using System;
    using Helpers;
    using System.IO;
    using System.Linq;

    [Authorize(Roles = "Admin")]
    public class DepartmentsController : Controller
    {
        private DataContext db = new DataContext();

        public ActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Import(ImportView view)
        {
            if (ModelState.IsValid)
            {
                var deparmentsFile = string.Empty;
                var citiesFile = string.Empty;
                var folder = "~/Content/Files";

                if (view.DeparmentsFile != null)
                {
                    deparmentsFile = FilesHelper.UploadPhoto(view.DeparmentsFile, folder);
                    deparmentsFile = Path.Combine(Server.MapPath(folder), deparmentsFile);
                }

                if (view.CitiesFile != null)
                {
                    citiesFile = FilesHelper.UploadPhoto(view.CitiesFile, folder);
                    citiesFile = Path.Combine(Server.MapPath(folder), citiesFile);
                }

                // Import Deparments
                var line = string.Empty;
                var deparmentsStream = new StreamReader(deparmentsFile);
                while ((line = deparmentsStream.ReadLine()) != null)
                {
                    var fields = line.Split(';');
                    var deparmentCode = int.Parse(fields[0]);
                    var oldDepartment = await db.Departments
                        .Where(d => d.DeparmentCode == deparmentCode)
                        .FirstOrDefaultAsync();
                    if (oldDepartment == null)
                    {
                        var department = new Department
                        {
                            Name = fields[2],
                            DeparmentCode = deparmentCode,
                        };

                        db.Departments.Add(department);
                        await db.SaveChangesAsync();
                    }
                }

                deparmentsStream.Close();

                // Import Cities
                line = string.Empty;
                var citiesStream = new StreamReader(citiesFile);
                while ((line = citiesStream.ReadLine()) != null)
                {
                    var fields = line.Split(';');
                    var deparmentCode = int.Parse(fields[3]);
                    var cityCode = int.Parse(fields[1]);
                    var oldCity = await db.Cities
                        .Where(c => c.CityCode == cityCode)
                        .FirstOrDefaultAsync();
                    if (oldCity == null)
                    {
                        var departament = await db.Departments
                            .Where(d => d.DeparmentCode == deparmentCode)
                            .FirstOrDefaultAsync();
                        if (departament != null)
                        {
                            var city = new City
                            {
                                CityCode = cityCode,
                                DepartmentId = departament.DepartmentId,
                                Name = fields[2],
                            };

                            db.Cities.Add(city);
                            await db.SaveChangesAsync();
                        }
                    }
                }

                citiesStream.Close();
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> CreateCity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var department = await db.Departments.FindAsync(id);

            if (department == null)
            {
                return HttpNotFound();
            }

            var city = new City { DepartmentId = department.DepartmentId, };
            return PartialView(city);
        }

        [HttpPost]
        public async Task<ActionResult> CreateCity(City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("Details/{0}", city.DepartmentId));
            }

            return View(city);
        }


        // GET: Departments
        public async Task<ActionResult> Index()
        {
            var departments = await db.Departments.ToListAsync();
            return View(departments);
        }

        // GET: Departments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = await db.Departments.FindAsync(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                try
                {
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null &&
                        ex.InnerException.InnerException != null &&
                        ex.InnerException.InnerException.Message.Contains("Index"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un departamento con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }
                }
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var department = await db.Departments.FindAsync(id);

            if (department == null)
            {
                return HttpNotFound();
            }

            return View(department);
        }

        // POST: Departments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                try
                {
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null &&
                        ex.InnerException.InnerException != null &&
                        ex.InnerException.InnerException.Message.Contains("Index"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un departamento con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }
                }
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = await db.Departments.FindAsync(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var department = await db.Departments.FindAsync(id);
            db.Departments.Remove(department);
            try
            {
                await db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                {
                    ModelState.AddModelError(string.Empty, "No se puede borrar el departamento porque tiene ciudades asociadas.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(department);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemoSinai/Views/Departments/Create.cshtml
@model DemoSinai.Models.Department

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoSinai/Views/Departments/CreateCity.cshtml
@model DemoSinai.Models.City

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar Ciudad" class="btn btn-primary" />
                @Html.ActionLink("Regresar", "Details", new { id=Model.DepartmentId }, new { @class="btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoSinai/Views/Departments/Delete.cshtml
@model DemoSinai.Models.Department

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemoSinai/Views/Departments/Details.cshtml
@model DemoSinai.Models.Department

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Nueva Ciudad", "CreateCity", 
    new { id = Model.DepartmentId }, 
    new { @class = "dialog-window btn btn-primary" })
    @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-success" })
</p>

@if (Model.Cities.Count == 0)
{
    <h3>No hay ciuadades registradas.</h3>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cities.FirstOrDefault().Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Cities)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Editar", "EditCity", new { id = item.CityId }, new { @class="btn btn-warning" })
                    @Html.ActionLink("Borrar", "DeleteCity", new { id = item.CityId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>
}

<div class="modal fade" id="AddCity" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title"></h2>
            </div>
            <div class="modal-body"><div class="te">Please wait...</div></div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $("body").on("click", "a.dialog-window", null, function (e) {
                e.preventDefault();
                var $link = $(this);
                var title = $link.text();
                $('#AddCity .modal-title').html(title);
                var url = $(this).attr('href');
                if (url.indexOf('#') == 0) {
                    $('#AddCity').modal('show');
                }
                else {
                    $.get(url, function (data) {
                        $('#AddCity .te').html(data);
                        $('#AddCity').modal();
                    }).success(function () { $('input:text:visible:first').focus(); });
                }
            });
        });
    </script>
}

DemoSinai/Views/Departments/Edit.cshtml
@model DemoSinai.Models.Department

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoSinai/Views/Departments/Import.cshtml
@model DemoSinai.Models.ImportView

@{
    ViewBag.Title = "Import";
}

<h2>Importar Departamentos y Ciudades</h2>

@using (Html.BeginForm("Import", "Departments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.DeparmentsFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.DeparmentsFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CitiesFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.CitiesFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Importar" class="btn btn-primary" />
                @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoSinai/Views/Departments/Index.cshtml
@model IEnumerable<DemoSinai.Models.Department>

@{
    ViewBag.Title = "Index";
}

<h2>Departamentos</h2>

<p>
    @Html.ActionLink("Nuevo", "Create", new { }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Importar", "Import", new { }, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            # de Ciudades
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cities.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DepartmentId }, new { @class = "btn btn-warning" })  
            @Html.ActionLink("Details", "Details", new { id=item.DepartmentId }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id=item.DepartmentId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>